// MonitoringCard.tsx (The container component)

"use client";

import React, { FC } from "react";
import MonitoringCardView from "./MonitoringCard.view";
import { MonitoringCardProps } from "./MonitoringCard.type";

const MonitoringCard: FC<MonitoringCardProps> = ({ cameraName }) => {
  // The HLS stream URL generated by our media-server.js
  // Ensure the server IP/hostname is accessible from the client's browser.
  // If running everything on the same machine, localhost is fine.
  const hlsStreamUrl = "http://localhost:8888/videostream.cgi";

  return (
    <MonitoringCardView cameraName={cameraName} hlsStreamUrl={hlsStreamUrl} />
  );
};

export default MonitoringCard;
